#!/bin/sh
#
# $Id$
#
# PROVIDE: si4
# REQUIRE: LOGIN

. /etc/rc.subr

name="si4"
rcvar="si4_enable"

pidfile="/var/run/si4/pid"
command="/usr/local/sbin/${name}"
command_args=""
procname="/usr/local/sbin/${name}"
command_interpreter="/usr/local/bin/ruby"

load_rc_config ${name}

: ${si4_enable:="NO"}

run_rc_command "$1"
#EOF
